//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace zmw.dev
{
    #region コンテキスト
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region コンストラクター
    
        /// <summary>
        /// アプリケーション構成ファイルの 'DatabaseEntities' セクションにある接続文字列を使用して新しい DatabaseEntities オブジェクトを初期化します。
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい DatabaseEntities オブジェクトを初期化します。
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい DatabaseEntities オブジェクトを初期化します。
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分メソッド
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<UserAccount> UserAccount
        {
            get
            {
                if ((_UserAccount == null))
                {
                    _UserAccount = base.CreateObjectSet<UserAccount>("UserAccount");
                }
                return _UserAccount;
            }
        }
        private ObjectSet<UserAccount> _UserAccount;

        #endregion
        #region AddTo メソッド
    
        /// <summary>
        /// UserAccount EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToUserAccount(UserAccount userAccount)
        {
            base.AddObject("UserAccount", userAccount);
        }

        #endregion
    }
    

    #endregion
    
    #region エンティティ
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zmw.dev.DatabaseEntities", Name="UserAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserAccount : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい UserAccount オブジェクトを作成します。
        /// </summary>
        /// <param name="userId">UserId プロパティの初期値。</param>
        /// <param name="accountId">AccountId プロパティの初期値。</param>
        /// <param name="password">Password プロパティの初期値。</param>
        /// <param name="insertTime">InsertTime プロパティの初期値。</param>
        /// <param name="deleteFlag">DeleteFlag プロパティの初期値。</param>
        public static UserAccount CreateUserAccount(global::System.String userId, global::System.String accountId, global::System.String password, global::System.DateTime insertTime, global::System.Byte deleteFlag)
        {
            UserAccount userAccount = new UserAccount();
            userAccount.UserId = userId;
            userAccount.AccountId = accountId;
            userAccount.Password = password;
            userAccount.InsertTime = insertTime;
            userAccount.DeleteFlag = deleteFlag;
            return userAccount;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AccountId
        {
            get
            {
                return _AccountId;
            }
            set
            {
                OnAccountIdChanging(value);
                ReportPropertyChanging("AccountId");
                _AccountId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AccountId");
                OnAccountIdChanged();
            }
        }
        private global::System.String _AccountId;
        partial void OnAccountIdChanging(global::System.String value);
        partial void OnAccountIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime InsertTime
        {
            get
            {
                return _InsertTime;
            }
            set
            {
                OnInsertTimeChanging(value);
                ReportPropertyChanging("InsertTime");
                _InsertTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InsertTime");
                OnInsertTimeChanged();
            }
        }
        private global::System.DateTime _InsertTime;
        partial void OnInsertTimeChanging(global::System.DateTime value);
        partial void OnInsertTimeChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte DeleteFlag
        {
            get
            {
                return _DeleteFlag;
            }
            set
            {
                OnDeleteFlagChanging(value);
                ReportPropertyChanging("DeleteFlag");
                _DeleteFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeleteFlag");
                OnDeleteFlagChanged();
            }
        }
        private global::System.Byte _DeleteFlag;
        partial void OnDeleteFlagChanging(global::System.Byte value);
        partial void OnDeleteFlagChanged();

        #endregion
    
    }

    #endregion
    
}
